const mongoose = require('mongoose');

const Schema = mongoose.Schema({
    userID: String,
    bank: Number,
    wallet: Number,
    game_cd: String,
    games_day_cd: String,
    game_count: Number,
    game_wins: Number,
    last_game: String,
    gamble_count: Number,
    gamble_cd: String,
    steal: Boolean,
    steal_amount: Number,
    steal_cd: String,
    spoof_cd: String,
    grab_cd: String,
    grab_count: Number,
    grab_wins: Number,
    coin_wins: Number,
    cmds_owned: [],
    game_completed: [],
    walletImages: [],
    walletImage: String,
    daily_cd: String,
    shishan_cd: String,
    send_amount: Number,
    send_cd: String,
    messageCount: Number, 
    klauen_cd: String,
    amerikasch_cd: String,
    byakugan_cd: String,
    sharingan_cd: String,
    amaterasu_cd: String,
    nightguy_cd: String,
    sosp_cd: String,
    gomugomu_cd: String,
    asapico_cd: String,
    game_battle_wins: Number,
    game_battle_cd: String,
    game_battle_count: Number,
    missions: []
})

module.exports = mongoose.model('users', Schema)